import Head from 'next/head'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import TodoList from '@/components/TodoList'
import { Database } from '@/lib/schema'
import { useEffect, useState } from 'react'


import { createClient } from '@supabase/supabase-js'
const supabaseUrl = 'https://ovfpegxizzlacduxfgqj.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92ZnBlZ3hpenpsYWNkdXhmZ3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NTI4MzAsImV4cCI6MjA1MjQyODgzMH0.nPYEjDGcWrzS9eWY1IuO-UacvnIr_DXuV2cVrugMXb8'
const supabase = createClient(supabaseUrl, supabaseKey)
          

export default function Home() {
  const session = useSession()
  const supabase = useSupabaseClient()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full bg-200">
        {!session ? (
          <div className="min-w-full min-h-screen flex items-center justify-center">
            <div className="w-full h-full flex justify-center items-center p-4">
              <div className="w-full h-full sm:h-auto sm:w-2/5 max-w-sm p-5 bg-white shadow flex flex-col text-base">
                <span className="font-sans text-4xl text-center pb-2 mb-1 border-b mx-4 align-center">
                  Login
                </span>

                <form method="get">

                <p className="font-small text-gray-500">Username</p>
                <input id="username" className="rounded w-full p-2 border-black" type="text" placeholder="enter username"/>

                <Auth supabaseClient={supabase} appearance={{ theme: ThemeSupa }} theme="dark" />

                </form>
                
              </div>
            </div>
          </div>
        ) : (
          <div
            className="w-full h-full flex flex-col justify-center items-center p-4"
            style={{ minWidth: 250, maxWidth: 600, margin: 'auto' }}
          >
            <TodoList session={session} />
            <button
              className="btn-black w-full mt-12"
              onClick={async () => {
                const { error } = await supabase.auth.signOut()
                if (error) console.log('Error logging out:', error.message)
              }}
            >
              Logout
            </button>
          </div>
        )}
      </div>
    </>
  )
}


const addToUsers = async (userText: string) => {

  const { data, error } = await supabase
  .from('users')
  .insert([
    { username: userText },
  ])
  .select()

}

let value = document.querySelectorAll('input')[0].value;
addToUsers(value);
