create table users (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    username text check (char_length(username) > 5)
);
alter table users enable row level security;
alter table users 
add constraint unique_usernames unique(username);
